project: 
  type: website
  output-dir: "html_output"

format:
  html:
    code-fold: false
    toc: true
    toc-location: right
    theme: United
    css: styles.css
    self-contained: true
    link-external-newwindow: true
    link-external-icon: false

execute: 
  echo: false
  warning: false
  message: false

website: 
  title: "PEV Project"
  repo-url: https://github.com/jhelvy/pingfan
  repo-actions: [edit, issue]
  sidebar: 
    style: docked
    background: light
    collapse-level: 1
    search: true
    contents: 
      - text: Home
        icon: house-door-fill
        href: index.qmd
      - text: Digest
        icon: clipboard-check
        href: qmd_notes/jp_proposal_digest.qmd
      - text: Terminologies
        icon: file-earmark-text
        href: qmd_notes/terminologies.qmd
      - section: Project
        icon: pencil-square
        contents: 
          - text: 1. Project Proposal
            href: qmd_project/01_project_proposal.qmd
          - text: 2. Survey Plan
            href: qmd_project/02_survey_plan.qmd
          - text: 3. Pilot Survey
            href: qmd_project/03_pilot_survey.qmd
          - text: 4. Pilot Analysis
            href: qmd_project/04_pilot_analysis.qmd
          - text: 5. Final Survey
            href: qmd_project/05_final_survey.qmd
          - text: 6. Final Analysis
            href: qmd_project/06_final_analysis.qmd
          - text: 7. Final Presentation
            href: qmd_project/07_final_presentation.qmd
      - section: Literature
        icon: book
        contents: 
          - text: Summary Table
            href: qmd_literature/00_summary_table.qmd
          - text: 01-logitr R Package
            href: qmd_literature/01_logitr_jp.qmd
          - text: 02-California Case
            href: qmd_literature/02_california_case_brian.qmd
          - text: 03-GPT for Research
            href: qmd_literature/03_using_gpt_for_market_research.qmd
          - text: 04-WTP for V2G
            href: qmd_literature/04_wtp_for_v2g.qmd
          - text: 05-Incentives to Shift
            href: qmd_literature/05_incentives_to_shift.qmd
          - text: 06-Incentives Difference
            href: qmd_literature/06_incentives_difference.qmd
          - text: 07-Stationary vs V2G
            href: qmd_literature/07_stationary_equivalency_of_v2g.qmd
          - text: 08-Sociotechnical of V2G
            href: qmd_literature/08_sociotechnical_of_v2g.qmd
            